services:
  gram-db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  gram-cache:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - cache_data:/var/lib/gram-cache/data
    ports:
      - "${CACHE_PORT}:35299"
    command: redis-server --port 35299 --requirepass xi9XILbY

volumes:
  postgres_data:
    driver: local
  cache_data:
    driver: local
