workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Gram Internal:
        inputs:
            - location: server/gen/http/openapi3.yaml
        overlays:
            - location: overlays/goa.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/gram-api-description
    Gram Public:
        inputs:
            - location: server/gen/http/openapi3.yaml
        overlays:
            - location: overlays/goa.yaml
            - location: overlays/public-sdk.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/gram-api-description
targets:
    gram-internal:
        target: typescript
        source: Gram Internal
        output: client/sdk
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/gram-api-description-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
    gram-public-py:
        target: python
        source: Gram Public
        publish:
            pypi:
                token: $pypi_token
        output: sdks/python
    gram-public-ts:
        target: typescript
        source: Gram Public
        publish:
            npm:
                token: $npm_token
        output: sdks/typescript
