workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Gram API Description:
        inputs:
            - location: server/gen/http/openapi3.yaml
        overlays:
            - location: overlays/goa.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/gram-api-description
targets:
    gram-internal:
        target: typescript
        source: Gram API Description
        output: client/sdk
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/gram-api-description-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
    gram-public:
        target: typescript
        source: Gram API Description
        output: sdks/typescript
