name: Migrations
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/migrations.yaml
      - 'server/migrations/*'
  pull_request:
    paths:
      - 'server/migrations/*'

jobs:
  lint:
    runs-on: ubicloud-standard-4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Mise
        uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Lint migrations
        run: |
          mise run lint:migrations \
            --github-token ${{ github.token }} \
            --github-event-path ${{ github.event_path }}