name: Pull Request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  server-build-lint-test:
    runs-on: ubicloud-standard-4
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: gram
          POSTGRES_PASSWORD: gram
          POSTGRES_DB: gram
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5439:5432
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Cache Go
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}
      - name: Build
        run: mise run build:server --readonly
      - uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          install-mode: none # installed by mise
          working-directory: server
      - name: Install Go tools
        run: go install tool
      - name: Run code generators
        run: mise run "gen:*"
      - name: Run "go mod tidy"
        run: mise run "go:tidy"
      - name: Check for dirty files
        run: mise run git:porcelain

  client-build-lint-test:
    runs-on: ubicloud-standard-4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Cache PNPM
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: ${{ env.GH_CACHE_PNPM_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_PNPM_KEY }}
            ${{ env.GH_CACHE_PNPM_KEY_PARTIAL }}
          path: |
            ${{ env.PNPM_STORE_PATH }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Prune PNPM store
        if: success()
        run: pnpm store prune
      - name: Check for dirty files
        run: mise run git:porcelain