name: Pull Request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  docker-build-server:
    runs-on: ubicloud-standard-4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Collect Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: speakeasy-api/gram
          tags: |
            type=sha,format=long
            type=sha,format=short
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Build Docker image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          push: false
          load: true
          context: ./server
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
      - name: Run Docker image
        run: docker run --rm speakeasy-api/gram:${{ steps.meta.outputs.version }} version

  server-build-lint-test:
    runs-on: ubicloud-standard-4
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: gram
          POSTGRES_PASSWORD: gram
          POSTGRES_DB: gram
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5439:5432
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Mise
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Cache Go
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_GO_KEY }}
            ${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}
      - name: Build
        run: mise run build:server --readonly
      - uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          install-mode: none # installed by mise
          working-directory: server
      - name: Install Go tools
        run: go install tool
      - name: Run code generators
        run: mise run "gen:*"
      - name: Run "go mod tidy"
        run: mise run go:tidy
      - name: Check for dirty files
        run: mise run git:porcelain

  client-build-lint-test:
    runs-on: ubicloud-standard-4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Mise
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Cache PNPM
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: ${{ env.GH_CACHE_PNPM_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_PNPM_KEY }}
            ${{ env.GH_CACHE_PNPM_KEY_PARTIAL }}
          path: |
            ${{ env.PNPM_STORE_PATH }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
        working-directory: client/dashboard
      - name: Prune PNPM store
        if: success()
        run: pnpm store prune
      - name: Check for dirty files
        run: mise run git:porcelain
  
  ts-sdk-build-lint:
    strategy:
      matrix:
        target: ["sdks/typescript", "client/sdk"]
    runs-on: ubicloud-standard-4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Mise
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Cache PNPM
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: ${{ env.GH_CACHE_PNPM_KEY }}
          restore-keys: |
            ${{ env.GH_CACHE_PNPM_KEY }}
            ${{ env.GH_CACHE_PNPM_KEY_PARTIAL }}
          path: |
            ${{ env.PNPM_STORE_PATH }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
        working-directory: ${{ matrix.target }}
      - name: Lint
        run: pnpm lint
        working-directory: ${{ matrix.target }}
      - name: Prune PNPM store
        if: success()
        run: pnpm store prune
      - name: Check for dirty files
        run: mise run git:porcelain

  py-sdk-build-lint:
    strategy:
      matrix:
        target:
          - path: sdks/python
            package: src/gram_ai
    runs-on: ubicloud-standard-4
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Mise
        uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Install dependencies
        run: poetry install --with=dev
        working-directory: ${{ matrix.target.path }}
      - name: Build
        run: poetry run python -m compileall -q .
        working-directory: ${{ matrix.target.path }}
      - name: Run pylint
        run: poetry run pylint -j=0 ${{ matrix.target.package }}
        working-directory: ${{ matrix.target.path }}
      - name: Run mypy
        run: poetry run mypy ${{ matrix.target.package }}
        working-directory: ${{ matrix.target.path }}