name: Pull Request
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Mise
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
        with:
          install: true
          cache: true
      - name: Prepare GitHub Actions environment
        run: mise run github
      - name: Cache Go
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: ${{ env.GH_CACHE_GO_KEY }}
          restore-keys: |
            go-${{ env.GH_CACHE_GO_KEY }}
            go-${{ env.GH_CACHE_GO_KEY_PARTIAL }}
          path: |
            ${{ env.GOCACHE }}
            ${{ env.GOMODCACHE }}
      - name: Build
        run: mise run build:server --readonly
      - uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          install-mode: none # installed by mise
          working-directory: server
